


import './globals.css';
import Navbar from './Components/Navbar';

export const metadata = {
  title: 'WikkiRocket',
  description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
      <html lang="en">
          <body className="bg-slate-800">
                <Navbar/>
                {children}
            </body>
      </html>
    );
};
